server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # Reverse proxy al backend del Lab P2 (mismo origen para el navegador: sin CORS)
  location /api/ {
    proxy_pass http://backend:8080;
    proxy_set_header Host $host;
    proxy_set_header Authorization $http_authorization;
  }
  location /auth/ {
    proxy_pass http://backend:8080;
    proxy_set_header Host $host;
  }

  # SPA: cualquier otra ruta la resuelve React Router
  location / {
    try_files $uri $uri/ /index.html;
  }
}
